{{- define "common.migration-config-configmap.tpl" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "fullname" . }}-conf-migration-configmap
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/resource-policy: keep
    helm.sh/hook-weight: "1"
data:
  flyway.conf: |
    flyway.schemas={{ .Release.Namespace  }}
{{- end -}}
{{- define "common.migration-config-configmap" -}}
{{- include "common.util.merge" (append . "common.migration-config-configmap.tpl") -}}
{{- end -}}
