{{- define "common.migration-job.tpl" }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ include "fullname" . }}-migration
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      {{- if .Values.migration.database.create }}
      initContainers:
      - name: {{ .Chart.Name }}-migration-create-db
        image: "docker.io/bitnami/postgresql:11"
        command: ["/bin/entrypoint.sh"]
        env:       
          - name: PGHOST
            value: {{ .Values.migration.database.host | quote }}
          - name: PGUSER
            value: {{ default "postgres" .Values.migration.database.postgresUser | quote }}
          - name: PGPASSWORD
            value: {{ default "postgres" .Values.migration.database.postgresPassword | quote }}
        volumeMounts:
          - name: createdb-script
            mountPath: /bin/entrypoint.sh
            readOnly: true
            subPath: entrypoint.sh
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-migration
        image: boxfuse/flyway:5.2.4
        args:
          - info
          - repair
          - migrate
          - info
        env:
          {{- with .Values.migration.database }}
          - name: FLYWAY_URL
            value: {{ printf "jdbc:postgresql://%s/%s-%s" .host $.Release.Namespace (default .name $.Chart.Name) | quote }}
          - name: FLYWAY_USER
            value: {{ .user | quote }}
          - name: FLYWAY_PASSWORD
            value: {{ .password | quote }} 
          {{- end }}
        volumeMounts:
          - mountPath: /flyway/sql
            name: sql
      volumes:
        - name: sql
          configMap:
            name: {{ include "fullname" . }}-sql-migration-configmap
        - name: createdb-script
          configMap:
            defaultMode: 0755
            name: {{ include "fullname" . }}-createdb-configmap
      restartPolicy: Never
  backoffLimit: 0
{{- end -}}
{{- define "common.migration-job" -}}
{{- include "common.util.merge" (append . "common.migration-job.tpl") -}}
{{- end -}}