{{- define "common.migration-sql-configmap.tpl" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "fullname" . }}-sql-migration-configmap
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/resource-policy: keep
    helm.sh/hook-weight: "1"
data:
  {{- (.Files.Glob "migrations/**.sql").AsConfig | nindent 2 }}
{{- end -}}
{{- define "common.migration-sql-configmap" -}}
{{- include "common.util.merge" (append . "common.migration-sql-configmap.tpl") -}}
{{- end -}}
