{{- define "common.mongo-init-job.tpl" }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ include "fullname" . }}-mongo-init-job
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: {{ .Chart.Name }}-mongo-init-job
        image: mongo:4.4
        command: [
          "sh", 
          "-c", 
          "mongo mongodb://{{.Values.mongo.user}}:{{.Values.mongo.password}}@{{.Values.mongo.url}}:27017/{{.Release.Namespace}}-{{.Values.mongo.database}}?authSource=admin /var/mongo/scripts/init.js",
        ]
        volumeMounts:
          - mountPath: /var/mongo/scripts
            name: scripts
      restartPolicy: Never
      volumes:
        - name: scripts
          configMap:
            name: {{ include "fullname" . }}-mongo-init-configmap
  backoffLimit: 0
{{- end -}}
{{- define "common.mongo-init-job" -}}
{{- include "common.util.merge" (append . "common.mongo-init-job.tpl") -}}
{{- end -}}