{{- define "common.deployment.tpl" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount | default "1" }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        timstamp: "{{ now | unixEpoch }}"
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: letsgo
      containers:
        - name: service
          image: "{{ .Values.image.repository }}/{{ .Chart.Name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort | default 3000 }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{ default "/" .Values.readinessPath}}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: API_HOST
              value: {{ include "apihost" . }}
            - name: WEB_HOST
              value: {{ include "webhost" . }}
          {{- with .Values.env }}
          {{- range $key, $val := . }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{ end -}}
          {{- end -}}
          {{- with .Values.volumes }}
          volumeMounts:
            {{- range . }}
            - mountPath: {{ .path }}/{{ .filename }}
              name: {{ .name }}
              subPath: {{ .filename }}
            {{ end -}}
          {{- end -}}
      {{- with .Values.volumes }}
      volumes:
        {{- range . }}
        - name: {{ .name }}
          configMap:
            name: {{ include "fullname" $ }}-{{ .name }}-configmap
        {{ end -}}
      {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
{{- define "common.deployment" -}}
{{- include "common.util.merge" (append . "common.deployment.tpl") -}}
{{- end -}}