{{- define "common.ingress.tpl" }}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "fullname" . -}}
{{- $svcPort := .Values.service.port | default "80" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"   
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
    {{- if eq .Release.Namespace "prod" }}
      - {{ printf "%s" .Values.service.apiHost | quote }}
    {{- else }}
      - {{ printf "%s.%s" .Release.Namespace .Values.service.apiHost | quote }}
    {{- end }}
      secretName: {{ .Release.Namespace }}-web-tls
  rules:
  {{- if eq .Release.Namespace "prod" }}
    - host: {{ printf "%s" .Values.service.apiHost | quote }}
  {{- else }}
    - host: {{ printf "%s.%s" .Release.Namespace .Values.service.apiHost | quote }}
  {{- end }}
      http:
        paths:
          - path: /{{- include "webpath" . }}(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ $svcPort }}
{{- end }}
{{- end -}}
{{- define "common.ingress" -}}
{{- include "common.util.merge" (append . "common.ingress.tpl") -}}
{{- end -}}